server:
  port: 8080
  servlet:
    context-path: /sharding-jdbc-simple-demo

spring:
  application:
    name: sharding-jdbc-simple-demo
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/order_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
        username: root
        password: root
    sharding:
      tables:
        t_order:
          actual-data-nodes: ds0.t_order_$->{1..2}
          key-generator:
            column: order_id
            type: SNOWFLAKE
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_$->{order_id % 2 + 1}
      binding-tables: t_order
    props:
      sql:
        show: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true


#以下是分片规则配置




